PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX wf-onto: <http://data.webfoundation.org/ontology/>
PREFIX qb: <http://purl.org/linked-data/cube#> 

SELECT DISTINCT ?observation ?element ?value
FROM <http://data.webfoundation.org/webindex/v2013/>
WHERE {
 ?subindex rdf:type cex:SubIndex .
 ?component rdf:type cex:Component .
 ?index rdf:type cex:Index .
 ?observation rdf:type qb:Observation .
 ?observation cex:indicator ?element .
 ?observation cex:value ?value .
 ?observation wf-onto:ref-area <http://data.webfoundation.org/webindex/v2013/country/FRA> .
FILTER (?element = ?subindex || ?element = ?component ||?element = ?index) .
}