prefix region: <http://data.webfoundation.org/webindex/v2013/region/> 
prefix indicator: <http://data.webfoundation.org/webindex/v2013/indicator/> 
prefix subindex: <http://data.webfoundation.org/webindex/v2013/subindex/> 
prefix sdmx-concept: <http://purl.org/linked-data/sdmx/2009/concept#> 
prefix cex:   <http://purl.org/weso/ontology/computex#> 
prefix qb:    <http://purl.org/linked-data/cube#> 
prefix sdmx-code: <http://purl.org/linked-data/sdmx/2009/code#> 
prefix wi-onto: <http://data.webfoundation.org/webindex/v2013/ontology/> 
prefix country: <http://data.webfoundation.org/webindex/v2013/country/> 
prefix dcterms: <http://purl.org/dc/terms/> 
prefix obs:   <http://data.webfoundation.org/webindex/v2013/observation/> 
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
prefix time:  <http://www.w3.org/2006/time#> 
prefix weightSchema: <http://data.webfoundation.org/webindex/v2013/weightSchema/> 
prefix dataset: <http://data.webfoundation.org/webindex/v2013/dataset/> 
prefix component: <http://data.webfoundation.org/webindex/v2013/component/> 
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix slice: <http://data.webfoundation.org/webindex/v2013/slice/> 
prefix smdx-attribute: <http://purl.org/linked-data/sdmx/2009/attribute#> 
prefix wi-org: <http://data.webfoundation.org/webindex/v2013/organization/> 
prefix skos:  <http://www.w3.org/2004/02/skos/core#> 
prefix smdx-subject: <http://purl.org/linked-data/sdmx/2009/subject#> 

SELECT ?countryCode ?countryName ?year ?indicatorCode ?value WHERE {
 ?obs a qb:Observation ;
      cex:indicator ?indicator ;
	  wi-onto:ref-area ?country ;
	  cex:value ?value ;
	  wi-onto:ref-year ?year .
	  
 ?country wi-onto:has-iso-alpha3-code ?countryCode ;
          rdfs:label ?countryName .
 ?indicator rdfs:label ?indicatorCode .
}